<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="com.traindb.pk.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Revenue Info</title>
</head>
<body>
	<%
	    
		try {
			//Get the database connection
			ApplicationDB db = new ApplicationDB();	
			Connection con = db.getConnection();		

			//Get the username and password from html text boxes
			
			String input = request.getParameter("input").equals("") ? null : request.getParameter("input");
			if(request.getParameter("byTransit")!=null){
				
				PreparedStatement st = con.prepareStatement("SELECT * FROM schedule WHERE transitName = ?");
				st.setString(1, input);
				ResultSet rs = st.executeQuery();
				if(rs.next()){
					PreparedStatement st2 = con.prepareStatement("SELECT sum(bookingFee) AS sum from reservation WHERE transitName = ?");					
					
					st2.setString(1, input);
					ResultSet rs2 = st2.executeQuery();
					if(rs2.next()){
						if(rs2.getString("sum")==null){

							out.print("Revenue generated by "+ input +": NONE");
						}
						else{

						out.print("Revenue generated by "+ input +": "+rs2.getString("sum"));
						}
						
					}
					else{

						out.print("Revenue generated by "+ input +": NONE");
						
					}
				}
				else{
					out.print("TRANSIT WITH THAT NAME DOES NOT EXIST");
					
				}
			}
			
			else if(request.getParameter("byCity")!=null){
				
				PreparedStatement st = con.prepareStatement("SELECT * FROM station WHERE city = ?");
				st.setString(1, input);
				ResultSet rs = st.executeQuery();
				if(rs.next()){
					PreparedStatement st2 = con.prepareStatement("SELECT SUM(bookingFee) AS sum FROM reservation r, schedule sc, station st WHERE r.transitName = sc.transitName AND sc.destinationSid = st.sid AND st.city = ?");					
					
					st2.setString(1, input);
					ResultSet rs2 = st2.executeQuery();
					if(rs2.next()){
						if(rs2.getString("sum")==null){

							out.print("Revenue generated by "+ input +": NONE");
						}
						else{

						out.print("Revenue generated by "+ input +": "+rs2.getString("sum"));
						}
					}
					else{

						out.print("Revenue generated by "+ input +": NONE");
						
					}
				}
				else{
					out.print("CITY STATION WITH THAT NAME DOES NOT EXIST");
					
				}
			}
			
			else if(request.getParameter("byUser")!=null){
				
				PreparedStatement st = con.prepareStatement("SELECT * FROM customers WHERE username = ?");
				st.setString(1, input);
				ResultSet rs = st.executeQuery();
				if(rs.next()){
					PreparedStatement st2 = con.prepareStatement("SELECT SUM(bookingFee) AS sum FROM reservation r WHERE username = ?");					
					
					st2.setString(1, input);
					ResultSet rs2 = st2.executeQuery();
					if(rs2.next()){
						
						if(rs2.getString("sum")==null){

							out.print("Revenue generated by "+ input +": NONE");
						}
						else{

						out.print("Revenue generated by "+ input +": "+rs2.getString("sum"));
						}
					}
					else{

						out.print("Revenue generated by "+ input +": NONE");
						
					}
				}
				else{
					out.print("USER WITH THAT USERNAME DOES NOT EXIST");
					
				}
			}
			
			
			
			
			//close the connection.
			db.closeConnection(con);
		} catch (Exception e) {
			out.print(e);
		}
	%>
	
	<form method="post" action="adminUI.jsp">
	<input type="submit" value="Admin home">
	</form>
</body>